In [1]:
import os
os.chdir('C:/Users/David/Desktop/Grad School/6. ISYE-6740 (CDA)/Project/Data/Cleaned')

In [25]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("clustered_data.csv")

In [4]:
array = df.values
X = array[:,4:38]
Y = array[:,38].astype('int')

df.head()

player  games_played  seasons_played  pos_mapped  avg_ts_percent  \
0     Toney Douglas           320               5         1.2          -0.092   
1   Hasheem Thabeet           181               3         5.0           0.652   
2      Scott Skiles           577               8         1.0           0.364   
3       Chris Kaman           617               9         5.0          -0.151   
4  Sergio Rodríguez           353               5         1.0          -1.053   

   avg_per  avg_mpg  avg_x3p_ar  avg_orb_percent  avg_drb_percent  ...  \
0   -0.252   -0.656       1.152           -0.550           -0.860  ...   
1   -1.144   -1.666      -1.097            1.140            0.626  ...   
2   -0.068    0.336       1.360           -1.339           -0.896  ...   
3    0.096    0.333      -1.078            0.862            1.621  ...   
4   -0.466   -1.121       0.571           -0.712           -0.999  ...   

   1T_ALL_NBA_total  2T_ALL_NBA_total  3T_ALL_NBA_total  1T_ALL_DEF_total  \
0                 0                 0                 0                 0   
1                 0                 0                 0                 0   
2                 0                 0                 0                 0   
3                 0                 0                 0                 0   
4                 0                 0                 0                 0   

   2T_ALL_DEF_total  DPOY_total  MIP_total  MVP_total  ROY_total  SMOY_total  
0                 0           0          0          0          0           0  
1                 0           0          0          0          0           0  
2                 0           0          1          0          0           0  
3                 0           0          0          0          0           0  
4                 0           0          0          0          0           0  

[5 rows x 51 columns]

In [5]:
X_sc = MinMaxScaler().fit_transform(X)
X_sc[: 5, : ]
#X_sc

array([[0.45230041, 0.33472273, 0.40885041, 0.25505906, 0.23297872,
        0.1835206 , 0.36659521, 0.54582975, 0.02270195, 0.36565381,
        0.48490698, 0.53971055, 0.31183831, 0.466701  , 0.40682458,
        0.41268227, 0.1987147 , 0.48867314, 0.32682004, 0.51445216,
        0.21892124, 0.2250737 , 0.18226002, 0.3419827 , 0.54540255,
        0.04485861, 0.26111319, 0.40234375, 0.47905909, 0.30811594,
        0.42038742, 0.40527302, 0.3609827 , 0.19639457],
       [0.57814614, 0.17306995, 0.16594517, 0.06929875, 0.59255319,
        0.49271744, 0.03410641, 0.2866724 , 0.52339833, 0.79737112,
        0.15672166, 0.39763502, 0.67083734, 0.16666667, 0.67467285,
        0.2633096 , 0.13292745, 0.65973185, 0.23684211, 0.20479498,
        0.05882353, 0.54863881, 0.4735289 , 0.02095808, 0.33033033,
        0.67699229, 0.54675632, 0.09284856, 0.36144578, 0.59115942,
        0.17103998, 0.65105893, 0.28146876, 0.11159071],
       [0.52943166, 0.36806814, 0.64742665, 0.2722392 , 0.06510638,
  

In [21]:
test = SelectKBest(score_func=chi2, k=5)
fit = test.fit(X_sc, Y)

np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X_sc)
# Summarize selected features
print(features[0:5,:])

[ 28.203  77.532  80.195  26.749 139.691 119.546  84.396  17.796 103.026
   6.226  23.031  40.162  38.415  57.375  14.755  65.421 100.677  33.065
  94.202  75.236  26.671 122.67  114.618  91.892  21.035 122.735   4.035
  31.729  52.021  36.633  67.745  21.834  68.463 139.257]
[[0.233 0.184 0.225 0.045 0.196]
 [0.593 0.493 0.549 0.677 0.112]
 [0.065 0.176 0.084 0.04  0.297]
 [0.533 0.7   0.561 0.493 0.192]
 [0.199 0.155 0.219 0.033 0.12 ]]


In [7]:
# Top 5 features (Chi-Squared statistical test)

#1. avg_orb_percent
#2. max_vorp
#3. max_blk_percent
#4. max_orb_percent
#5. avg_drb_percent

In [33]:
estimator = svm.SVC(kernel='linear')
rfe = RFE(estimator=estimator, n_features_to_select=5)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

Num Features: 5
Selected Features: [False False False False  True False False False False False False False
 False  True False  True False False  True False False False False False
 False False False False False False False False False  True]
Feature Ranking: [ 7  8 12 14  1  2 27 26  3 25 29 19 15  1 20  1 16 22  1  6 28  9 13 21
 23 18 30 17  4  5 10 11 24  1]


In [ ]:
# Top 5 features (RFE)

#1. max_vorp
#2. avg_obpm
#3. avg_orb_percent
#4. avg_bpm
#5. max_per